// Login
POST http://localhost:3000/api/login
content-type: application/json

{
    "email": "tomas@gmail.com",
    "password": "123456"
}

###

// Get all ideas for admin
GET http://localhost:3000/api/admin/ideas
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbWFzQGdtYWlsLmNvbSIsInN1YiI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA4MzMzNjI0LCJleHAiOjE3MDgzMzcyMjR9.YmYraq7pMt7xyJyB4avQxW7xwxemQYfBFdE_WSbmRUo



###

// Get accepted ideas
GET http://localhost:3000/api/ideas

###

// add ideas
post http://localhost:3000/api/addIdea
content-type: application/json

{
    "title": "text",
    "content": "contentas",
    "img": "https://www.diena.lt/sites/default/files/styles/800x600/public/Vilniausdiena/Vartotoju%20zona/Erika%20Mick%C5%ABnait%C4%97/99_3_44.jpg?itok=Z4fIFhCE",
    "need": 500,
    "person" : "tomas"
}

###

// accepted idea
PUT http://localhost:3000/api/admin/acceptIdea/2

###

// Delete idea
DELETE http://localhost:3000/api/admin/ideas/5


###

post http://localhost:3000/api/donate
content-type: application/json

{
    "person": "Tomas",
    "amount": 5,
    "ideaId": 9
}

###

GET http://localhost:3000/api/donated/9


